export const projects = [
	{
		img: 'https://user-images.githubusercontent.com/95927107/169561482-ed41369f-070f-400a-b71e-cb6d14149820.png',
		title: 'React Project',
		des: 'This is a solo project that I built using complete MERN stack. This project have all the necessary functionalities of an E-Commerce website. Built in just 10 days',
		demo: '',
		live: 'https://react-store-prashant-sl.netlify.app/',
		gitHub: 'https://github.com/Prashant-SL/ReactProject',
		technologies: [
			'React JS',
			'HTML',
			'Chakra UI',
			'CSS',
			'JavaScript',
			'Node.js',
			'Express.js',
			'MongoDB',
		],
	},
	{
		img: 'https://raw.githubusercontent.com/ankush4gupta/ajio_backend/Prashant-SL/AJIO%20CLONE%20HOMEPAGE.jpeg',
		title: 'Ajio.com Clone',
		des: 'This is a team project where we worked on cloning the Ajio website. Here users can buy fashion & lifestyle products. We created the following things Navbar, Home Page, Product Page, Cart Page, Payment Page, Wishlist Page. A team of 5 members, done in 5 days',
		demo: '',
		live: 'https://ajio-masai.herokuapp.com/',
		gitHub: 'https://github.com/ankush4gupta/ajio_backend',
		technologies: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'Express.js', 'MongoDB'],
	},
	{
		img: 'https://raw.githubusercontent.com/Niks14041/Pantloons-clone/prashant/Pantaloons%20Clone.jpeg',
		title: 'Pantaloons.com Clone',
		des: "Pantaloons.com is an Online Shopping Site for Men's and Women's Clothing. We built interface using HTML, CSS & DOM where users can add items to the cart, use filters to check items by Price and category, and added login functionality.",
		demo: '',
		live: 'https://pantaloons-clone-project.netlify.app/homepage.html',
		gitHub: 'https://github.com/Niks14041/Pantloons-clone',
		technologies: ['HTML', 'CSS', 'JavaScript', 'DOM'],
	},
];
